// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMcd_fzFLT3Yy53K3rRsCn6SWaOVHSeUk',
    appId: '1:470779263656:web:791971a59b9b9d3e8ee09d',
    messagingSenderId: '470779263656',
    projectId: 'motasimfuadpt',
    authDomain: 'motasimfuadpt.firebaseapp.com',
    storageBucket: 'motasimfuadpt.firebasestorage.app',
    measurementId: 'G-8WCG25F5M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw-F9G2gMR6TzCc7hBUtc30OsPKtlpXj8',
    appId: '1:470779263656:android:61c813056a927b3f8ee09d',
    messagingSenderId: '470779263656',
    projectId: 'motasimfuadpt',
    storageBucket: 'motasimfuadpt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhrzq3SpSNqfuaewDILXjJdyVpVmLGxsM',
    appId: '1:470779263656:ios:a36bbe686b96d3c08ee09d',
    messagingSenderId: '470779263656',
    projectId: 'motasimfuadpt',
    storageBucket: 'motasimfuadpt.firebasestorage.app',
    iosBundleId: 'com.example.motasimfuadpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhrzq3SpSNqfuaewDILXjJdyVpVmLGxsM',
    appId: '1:470779263656:ios:a36bbe686b96d3c08ee09d',
    messagingSenderId: '470779263656',
    projectId: 'motasimfuadpt',
    storageBucket: 'motasimfuadpt.firebasestorage.app',
    iosBundleId: 'com.example.motasimfuadpt',
  );
}
